//------------------------------------------------------------------------------
// <auto-generated>
//     Questo codice è stato generato da uno strumento.
//
//     Le modifiche apportate a questo file possono causare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBogglerServer
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Board", Namespace="http://tempuri.org/")]
    public partial class Board : object
    {
        
        private string LocaleIDField;
        
        private WebBogglerServer.Dice[] DicesVectorField;
        
        private int WordCountField;
        
        private long GameSerialField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LocaleID
        {
            get
            {
                return this.LocaleIDField;
            }
            set
            {
                this.LocaleIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public WebBogglerServer.Dice[] DicesVector
        {
            get
            {
                return this.DicesVectorField;
            }
            set
            {
                this.DicesVectorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int WordCount
        {
            get
            {
                return this.WordCountField;
            }
            set
            {
                this.WordCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long GameSerial
        {
            get
            {
                return this.GameSerialField;
            }
            set
            {
                this.GameSerialField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dice", Namespace="http://tempuri.org/")]
    public partial class Dice : object
    {
        
        private int IndexField;
        
        private int RotationField;
        
        private string LetterField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Index
        {
            get
            {
                return this.IndexField;
            }
            set
            {
                this.IndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Rotation
        {
            get
            {
                return this.RotationField;
            }
            set
            {
                this.RotationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Letter
        {
            get
            {
                return this.LetterField;
            }
            set
            {
                this.LetterField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WordList", Namespace="http://tempuri.org/")]
    public partial class WordList : object
    {
        
        private WebBogglerServer.Word[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WebBogglerServer.Word[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Word", Namespace="http://tempuri.org/")]
    public partial class Word : object
    {
        
        private WebBogglerServer.Dice[] DicePathField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WebBogglerServer.Dice[] DicePath
        {
            get
            {
                return this.DicePathField;
            }
            set
            {
                this.DicePathField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Players", Namespace="http://tempuri.org/")]
    public partial class Players : object
    {
        
        private WebBogglerServer.Player[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WebBogglerServer.Player[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://tempuri.org/")]
    public partial class Player : object
    {
        
        private string IDField;
        
        private string NickNameField;
        
        private int RankField;
        
        private int ScoreField;
        
        private int RecordField;
        
        private int TotalRoundPlayedField;
        
        private int TotalWinningRoundField;
        
        private double WinPercentField;
        
        private bool IsLocalField;
        
        private bool IsGuestField;
        
        private WebBogglerServer.WordList WordListField;
        
        private int TotalWordsCountField;
        
        private bool IsReadyField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NickName
        {
            get
            {
                return this.NickNameField;
            }
            set
            {
                this.NickNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Rank
        {
            get
            {
                return this.RankField;
            }
            set
            {
                this.RankField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Score
        {
            get
            {
                return this.ScoreField;
            }
            set
            {
                this.ScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Record
        {
            get
            {
                return this.RecordField;
            }
            set
            {
                this.RecordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int TotalRoundPlayed
        {
            get
            {
                return this.TotalRoundPlayedField;
            }
            set
            {
                this.TotalRoundPlayedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int TotalWinningRound
        {
            get
            {
                return this.TotalWinningRoundField;
            }
            set
            {
                this.TotalWinningRoundField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public double WinPercent
        {
            get
            {
                return this.WinPercentField;
            }
            set
            {
                this.WinPercentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool IsLocal
        {
            get
            {
                return this.IsLocalField;
            }
            set
            {
                this.IsLocalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public bool IsGuest
        {
            get
            {
                return this.IsGuestField;
            }
            set
            {
                this.IsGuestField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public WebBogglerServer.WordList WordList
        {
            get
            {
                return this.WordListField;
            }
            set
            {
                this.WordListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int TotalWordsCount
        {
            get
            {
                return this.TotalWordsCountField;
            }
            set
            {
                this.TotalWordsCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public bool IsReady
        {
            get
            {
                return this.IsReadyField;
            }
            set
            {
                this.IsReadyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameInfo", Namespace="http://tempuri.org/")]
    public partial class GameInfo : object
    {
        
        private string ServerTimeUTCField;
        
        private int RoundElapsedTimeMSField;
        
        private int RoundDurationMSField;
        
        private int DeadTimeAmountMSField;
        
        private string RoomStateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ServerTimeUTC
        {
            get
            {
                return this.ServerTimeUTCField;
            }
            set
            {
                this.ServerTimeUTCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int RoundElapsedTimeMS
        {
            get
            {
                return this.RoundElapsedTimeMSField;
            }
            set
            {
                this.RoundElapsedTimeMSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int RoundDurationMS
        {
            get
            {
                return this.RoundDurationMSField;
            }
            set
            {
                this.RoundDurationMSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int DeadTimeAmountMS
        {
            get
            {
                return this.DeadTimeAmountMSField;
            }
            set
            {
                this.DeadTimeAmountMSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string RoomState
        {
            get
            {
                return this.RoomStateField;
            }
            set
            {
                this.RoomStateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebBogglerServer.IServiceWebBoggler")]
    public interface IServiceWebBoggler
    {
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento localeID dello spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWebBoggler/GetBoard", ReplyAction="http://tempuri.org/IServiceWebBoggler/GetBoardResponse")]
        WebBogglerServer.GetBoardResponse GetBoard(WebBogglerServer.GetBoardRequest request);
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento word dello spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWebBoggler/CheckWord", ReplyAction="http://tempuri.org/IServiceWebBoggler/CheckWordResponse")]
        WebBogglerServer.CheckWordResponse CheckWord(WebBogglerServer.CheckWordRequest request);
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento wordList dello spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWebBoggler/SendWordList", ReplyAction="http://tempuri.org/IServiceWebBoggler/SendWordListResponse")]
        WebBogglerServer.SendWordListResponse SendWordList(WebBogglerServer.SendWordListRequest request);
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento clientID dello spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWebBoggler/Join", ReplyAction="http://tempuri.org/IServiceWebBoggler/JoinResponse")]
        WebBogglerServer.JoinResponse Join(WebBogglerServer.JoinRequest request);
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento clientID dello spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWebBoggler/Leave", ReplyAction="http://tempuri.org/IServiceWebBoggler/LeaveResponse")]
        WebBogglerServer.LeaveResponse Leave(WebBogglerServer.LeaveRequest request);
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento clientID dello spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWebBoggler/GetPlayers", ReplyAction="http://tempuri.org/IServiceWebBoggler/GetPlayersResponse")]
        WebBogglerServer.GetPlayersResponse GetPlayers(WebBogglerServer.GetPlayersRequest request);
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento GetSolutionResult dello spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWebBoggler/GetSolution", ReplyAction="http://tempuri.org/IServiceWebBoggler/GetSolutionResponse")]
        WebBogglerServer.GetSolutionResponse GetSolution(WebBogglerServer.GetSolutionRequest request);
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento ObserveResult dello spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWebBoggler/Observe", ReplyAction="http://tempuri.org/IServiceWebBoggler/ObserveResponse")]
        WebBogglerServer.ObserveResponse Observe(WebBogglerServer.ObserveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWebBoggler/IsServerAlive", ReplyAction="http://tempuri.org/IServiceWebBoggler/IsServerAliveResponse")]
        bool IsServerAlive();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBoardRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBoard", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.GetBoardRequestBody Body;
        
        public GetBoardRequest()
        {
        }
        
        public GetBoardRequest(WebBogglerServer.GetBoardRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBoardRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string localeID;
        
        public GetBoardRequestBody()
        {
        }
        
        public GetBoardRequestBody(string localeID)
        {
            this.localeID = localeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBoardResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBoardResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.GetBoardResponseBody Body;
        
        public GetBoardResponse()
        {
        }
        
        public GetBoardResponse(WebBogglerServer.GetBoardResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBoardResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebBogglerServer.Board GetBoardResult;
        
        public GetBoardResponseBody()
        {
        }
        
        public GetBoardResponseBody(WebBogglerServer.Board GetBoardResult)
        {
            this.GetBoardResult = GetBoardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckWordRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckWord", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.CheckWordRequestBody Body;
        
        public CheckWordRequest()
        {
        }
        
        public CheckWordRequest(WebBogglerServer.CheckWordRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckWordRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string word;
        
        public CheckWordRequestBody()
        {
        }
        
        public CheckWordRequestBody(string word)
        {
            this.word = word;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckWordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckWordResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.CheckWordResponseBody Body;
        
        public CheckWordResponse()
        {
        }
        
        public CheckWordResponse(WebBogglerServer.CheckWordResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckWordResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckWordResult;
        
        public CheckWordResponseBody()
        {
        }
        
        public CheckWordResponseBody(bool CheckWordResult)
        {
            this.CheckWordResult = CheckWordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWordListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWordList", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.SendWordListRequestBody Body;
        
        public SendWordListRequest()
        {
        }
        
        public SendWordListRequest(WebBogglerServer.SendWordListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendWordListRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebBogglerServer.WordList wordList;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ClientID;
        
        public SendWordListRequestBody()
        {
        }
        
        public SendWordListRequestBody(WebBogglerServer.WordList wordList, string ClientID)
        {
            this.wordList = wordList;
            this.ClientID = ClientID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWordListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWordListResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.SendWordListResponseBody Body;
        
        public SendWordListResponse()
        {
        }
        
        public SendWordListResponse(WebBogglerServer.SendWordListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendWordListResponseBody
    {
        
        public SendWordListResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JoinRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Join", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.JoinRequestBody Body;
        
        public JoinRequest()
        {
        }
        
        public JoinRequest(WebBogglerServer.JoinRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JoinRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        public JoinRequestBody()
        {
        }
        
        public JoinRequestBody(string clientID, string name)
        {
            this.clientID = clientID;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JoinResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JoinResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.JoinResponseBody Body;
        
        public JoinResponse()
        {
        }
        
        public JoinResponse(WebBogglerServer.JoinResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JoinResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool JoinResult;
        
        public JoinResponseBody()
        {
        }
        
        public JoinResponseBody(bool JoinResult)
        {
            this.JoinResult = JoinResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LeaveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Leave", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.LeaveRequestBody Body;
        
        public LeaveRequest()
        {
        }
        
        public LeaveRequest(WebBogglerServer.LeaveRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LeaveRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientID;
        
        public LeaveRequestBody()
        {
        }
        
        public LeaveRequestBody(string clientID)
        {
            this.clientID = clientID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LeaveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LeaveResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.LeaveResponseBody Body;
        
        public LeaveResponse()
        {
        }
        
        public LeaveResponse(WebBogglerServer.LeaveResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LeaveResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LeaveResult;
        
        public LeaveResponseBody()
        {
        }
        
        public LeaveResponseBody(bool LeaveResult)
        {
            this.LeaveResult = LeaveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPlayersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPlayers", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.GetPlayersRequestBody Body;
        
        public GetPlayersRequest()
        {
        }
        
        public GetPlayersRequest(WebBogglerServer.GetPlayersRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPlayersRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientID;
        
        public GetPlayersRequestBody()
        {
        }
        
        public GetPlayersRequestBody(string clientID)
        {
            this.clientID = clientID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPlayersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPlayersResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.GetPlayersResponseBody Body;
        
        public GetPlayersResponse()
        {
        }
        
        public GetPlayersResponse(WebBogglerServer.GetPlayersResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPlayersResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebBogglerServer.Players GetPlayersResult;
        
        public GetPlayersResponseBody()
        {
        }
        
        public GetPlayersResponseBody(WebBogglerServer.Players GetPlayersResult)
        {
            this.GetPlayersResult = GetPlayersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSolutionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSolution", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.GetSolutionRequestBody Body;
        
        public GetSolutionRequest()
        {
        }
        
        public GetSolutionRequest(WebBogglerServer.GetSolutionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSolutionRequestBody
    {
        
        public GetSolutionRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSolutionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSolutionResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.GetSolutionResponseBody Body;
        
        public GetSolutionResponse()
        {
        }
        
        public GetSolutionResponse(WebBogglerServer.GetSolutionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSolutionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebBogglerServer.WordList GetSolutionResult;
        
        public GetSolutionResponseBody()
        {
        }
        
        public GetSolutionResponseBody(WebBogglerServer.WordList GetSolutionResult)
        {
            this.GetSolutionResult = GetSolutionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObserveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Observe", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.ObserveRequestBody Body;
        
        public ObserveRequest()
        {
        }
        
        public ObserveRequest(WebBogglerServer.ObserveRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObserveRequestBody
    {
        
        public ObserveRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObserveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObserveResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.ObserveResponseBody Body;
        
        public ObserveResponse()
        {
        }
        
        public ObserveResponse(WebBogglerServer.ObserveResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObserveResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebBogglerServer.GameInfo ObserveResult;
        
        public ObserveResponseBody()
        {
        }
        
        public ObserveResponseBody(WebBogglerServer.GameInfo ObserveResult)
        {
            this.ObserveResult = ObserveResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IServiceWebBogglerChannel : WebBogglerServer.IServiceWebBoggler, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ServiceWebBogglerClient : System.ServiceModel.ClientBase<WebBogglerServer.IServiceWebBoggler>, WebBogglerServer.IServiceWebBoggler
    {
        
        /// <summary>
        /// Implementare questo metodo parziale per configurare l'endpoint servizio.
        /// </summary>
        /// <param name="serviceEndpoint">Endpoint da configurare</param>
        /// <param name="clientCredentials">Credenziali del client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceWebBogglerClient() : 
                base(ServiceWebBogglerClient.GetDefaultBinding(), ServiceWebBogglerClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceWebBoggler.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceWebBogglerClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceWebBogglerClient.GetBindingForEndpoint(endpointConfiguration), ServiceWebBogglerClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceWebBogglerClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceWebBogglerClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceWebBogglerClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceWebBogglerClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceWebBogglerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebBogglerServer.GetBoardResponse WebBogglerServer.IServiceWebBoggler.GetBoard(WebBogglerServer.GetBoardRequest request)
        {
            return base.Channel.GetBoard(request);
        }
        
        public WebBogglerServer.Board GetBoard(string localeID)
        {
            WebBogglerServer.GetBoardRequest inValue = new WebBogglerServer.GetBoardRequest();
            inValue.Body = new WebBogglerServer.GetBoardRequestBody();
            inValue.Body.localeID = localeID;
            WebBogglerServer.GetBoardResponse retVal = ((WebBogglerServer.IServiceWebBoggler)(this)).GetBoard(inValue);
            return retVal.Body.GetBoardResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebBogglerServer.CheckWordResponse WebBogglerServer.IServiceWebBoggler.CheckWord(WebBogglerServer.CheckWordRequest request)
        {
            return base.Channel.CheckWord(request);
        }
        
        public bool CheckWord(string word)
        {
            WebBogglerServer.CheckWordRequest inValue = new WebBogglerServer.CheckWordRequest();
            inValue.Body = new WebBogglerServer.CheckWordRequestBody();
            inValue.Body.word = word;
            WebBogglerServer.CheckWordResponse retVal = ((WebBogglerServer.IServiceWebBoggler)(this)).CheckWord(inValue);
            return retVal.Body.CheckWordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebBogglerServer.SendWordListResponse WebBogglerServer.IServiceWebBoggler.SendWordList(WebBogglerServer.SendWordListRequest request)
        {
            return base.Channel.SendWordList(request);
        }
        
        public void SendWordList(WebBogglerServer.WordList wordList, string ClientID)
        {
            WebBogglerServer.SendWordListRequest inValue = new WebBogglerServer.SendWordListRequest();
            inValue.Body = new WebBogglerServer.SendWordListRequestBody();
            inValue.Body.wordList = wordList;
            inValue.Body.ClientID = ClientID;
            WebBogglerServer.SendWordListResponse retVal = ((WebBogglerServer.IServiceWebBoggler)(this)).SendWordList(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebBogglerServer.JoinResponse WebBogglerServer.IServiceWebBoggler.Join(WebBogglerServer.JoinRequest request)
        {
            return base.Channel.Join(request);
        }
        
        public bool Join(string clientID, string name)
        {
            WebBogglerServer.JoinRequest inValue = new WebBogglerServer.JoinRequest();
            inValue.Body = new WebBogglerServer.JoinRequestBody();
            inValue.Body.clientID = clientID;
            inValue.Body.name = name;
            WebBogglerServer.JoinResponse retVal = ((WebBogglerServer.IServiceWebBoggler)(this)).Join(inValue);
            return retVal.Body.JoinResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebBogglerServer.LeaveResponse WebBogglerServer.IServiceWebBoggler.Leave(WebBogglerServer.LeaveRequest request)
        {
            return base.Channel.Leave(request);
        }
        
        public bool Leave(string clientID)
        {
            WebBogglerServer.LeaveRequest inValue = new WebBogglerServer.LeaveRequest();
            inValue.Body = new WebBogglerServer.LeaveRequestBody();
            inValue.Body.clientID = clientID;
            WebBogglerServer.LeaveResponse retVal = ((WebBogglerServer.IServiceWebBoggler)(this)).Leave(inValue);
            return retVal.Body.LeaveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebBogglerServer.GetPlayersResponse WebBogglerServer.IServiceWebBoggler.GetPlayers(WebBogglerServer.GetPlayersRequest request)
        {
            return base.Channel.GetPlayers(request);
        }
        
        public WebBogglerServer.Players GetPlayers(string clientID)
        {
            WebBogglerServer.GetPlayersRequest inValue = new WebBogglerServer.GetPlayersRequest();
            inValue.Body = new WebBogglerServer.GetPlayersRequestBody();
            inValue.Body.clientID = clientID;
            WebBogglerServer.GetPlayersResponse retVal = ((WebBogglerServer.IServiceWebBoggler)(this)).GetPlayers(inValue);
            return retVal.Body.GetPlayersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebBogglerServer.GetSolutionResponse WebBogglerServer.IServiceWebBoggler.GetSolution(WebBogglerServer.GetSolutionRequest request)
        {
            return base.Channel.GetSolution(request);
        }
        
        public WebBogglerServer.WordList GetSolution()
        {
            WebBogglerServer.GetSolutionRequest inValue = new WebBogglerServer.GetSolutionRequest();
            inValue.Body = new WebBogglerServer.GetSolutionRequestBody();
            WebBogglerServer.GetSolutionResponse retVal = ((WebBogglerServer.IServiceWebBoggler)(this)).GetSolution(inValue);
            return retVal.Body.GetSolutionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebBogglerServer.ObserveResponse WebBogglerServer.IServiceWebBoggler.Observe(WebBogglerServer.ObserveRequest request)
        {
            return base.Channel.Observe(request);
        }
        
        public WebBogglerServer.GameInfo Observe()
        {
            WebBogglerServer.ObserveRequest inValue = new WebBogglerServer.ObserveRequest();
            inValue.Body = new WebBogglerServer.ObserveRequestBody();
            WebBogglerServer.ObserveResponse retVal = ((WebBogglerServer.IServiceWebBoggler)(this)).Observe(inValue);
            return retVal.Body.ObserveResult;
        }
        
        public bool IsServerAlive()
        {
            return base.Channel.IsServerAlive();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceWebBoggler))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("L\'endpoint denominato \'{0}\' non è stato trovato.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceWebBoggler))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:54057/ServiceWebBoggler.svc");
            }
            throw new System.InvalidOperationException(string.Format("L\'endpoint denominato \'{0}\' non è stato trovato.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceWebBogglerClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceWebBoggler);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceWebBogglerClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceWebBoggler);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceWebBoggler,
        }
    }
}
