//------------------------------------------------------------------------------
// <auto-generated>
//     Questo codice è stato generato da uno strumento.
//
//     Le modifiche apportate a questo file possono causare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBogglerServer
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Board", Namespace="http://tempuri.org/")]
    public partial class Board : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string LocaleIDField;
        
        private WebBogglerServer.Dice[] DicesVectorField;
        
        private int WordCountField;
        
        private long GameSerialField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LocaleID
        {
            get
            {
                return this.LocaleIDField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LocaleIDField, value) != true))
                {
                    this.LocaleIDField = value;
                    this.RaisePropertyChanged("LocaleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public WebBogglerServer.Dice[] DicesVector
        {
            get
            {
                return this.DicesVectorField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DicesVectorField, value) != true))
                {
                    this.DicesVectorField = value;
                    this.RaisePropertyChanged("DicesVector");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int WordCount
        {
            get
            {
                return this.WordCountField;
            }
            set
            {
                if ((this.WordCountField.Equals(value) != true))
                {
                    this.WordCountField = value;
                    this.RaisePropertyChanged("WordCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long GameSerial
        {
            get
            {
                return this.GameSerialField;
            }
            set
            {
                if ((this.GameSerialField.Equals(value) != true))
                {
                    this.GameSerialField = value;
                    this.RaisePropertyChanged("GameSerial");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dice", Namespace="http://tempuri.org/")]
    public partial class Dice : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private int IndexField;
        
        private int RotationField;
        
        private string LetterField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Index
        {
            get
            {
                return this.IndexField;
            }
            set
            {
                if ((this.IndexField.Equals(value) != true))
                {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Rotation
        {
            get
            {
                return this.RotationField;
            }
            set
            {
                if ((this.RotationField.Equals(value) != true))
                {
                    this.RotationField = value;
                    this.RaisePropertyChanged("Rotation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Letter
        {
            get
            {
                return this.LetterField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LetterField, value) != true))
                {
                    this.LetterField = value;
                    this.RaisePropertyChanged("Letter");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WordList", Namespace="http://tempuri.org/")]
    public partial class WordList : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private WebBogglerServer.Word[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WebBogglerServer.Word[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ItemsField, value) != true))
                {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Word", Namespace="http://tempuri.org/")]
    public partial class Word : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private WebBogglerServer.Dice[] DicePathField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WebBogglerServer.Dice[] DicePath
        {
            get
            {
                return this.DicePathField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DicePathField, value) != true))
                {
                    this.DicePathField = value;
                    this.RaisePropertyChanged("DicePath");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Players", Namespace="http://tempuri.org/")]
    public partial class Players : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private WebBogglerServer.Player[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WebBogglerServer.Player[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ItemsField, value) != true))
                {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://tempuri.org/")]
    public partial class Player : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string IDField;
        
        private string NickNameField;
        
        private int RankField;
        
        private int ScoreField;
        
        private int RecordField;
        
        private int TotalRoundPlayedField;
        
        private int TotalWinningRoundField;
        
        private double WinPercentField;
        
        private bool IsLocalField;
        
        private bool IsGuestField;
        
        private WebBogglerServer.WordList WordListField;
        
        private int TotalWordsCountField;
        
        private bool IsReadyField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                if ((object.ReferenceEquals(this.IDField, value) != true))
                {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NickName
        {
            get
            {
                return this.NickNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NickNameField, value) != true))
                {
                    this.NickNameField = value;
                    this.RaisePropertyChanged("NickName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Rank
        {
            get
            {
                return this.RankField;
            }
            set
            {
                if ((this.RankField.Equals(value) != true))
                {
                    this.RankField = value;
                    this.RaisePropertyChanged("Rank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Score
        {
            get
            {
                return this.ScoreField;
            }
            set
            {
                if ((this.ScoreField.Equals(value) != true))
                {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Record
        {
            get
            {
                return this.RecordField;
            }
            set
            {
                if ((this.RecordField.Equals(value) != true))
                {
                    this.RecordField = value;
                    this.RaisePropertyChanged("Record");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int TotalRoundPlayed
        {
            get
            {
                return this.TotalRoundPlayedField;
            }
            set
            {
                if ((this.TotalRoundPlayedField.Equals(value) != true))
                {
                    this.TotalRoundPlayedField = value;
                    this.RaisePropertyChanged("TotalRoundPlayed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int TotalWinningRound
        {
            get
            {
                return this.TotalWinningRoundField;
            }
            set
            {
                if ((this.TotalWinningRoundField.Equals(value) != true))
                {
                    this.TotalWinningRoundField = value;
                    this.RaisePropertyChanged("TotalWinningRound");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public double WinPercent
        {
            get
            {
                return this.WinPercentField;
            }
            set
            {
                if ((this.WinPercentField.Equals(value) != true))
                {
                    this.WinPercentField = value;
                    this.RaisePropertyChanged("WinPercent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool IsLocal
        {
            get
            {
                return this.IsLocalField;
            }
            set
            {
                if ((this.IsLocalField.Equals(value) != true))
                {
                    this.IsLocalField = value;
                    this.RaisePropertyChanged("IsLocal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public bool IsGuest
        {
            get
            {
                return this.IsGuestField;
            }
            set
            {
                if ((this.IsGuestField.Equals(value) != true))
                {
                    this.IsGuestField = value;
                    this.RaisePropertyChanged("IsGuest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public WebBogglerServer.WordList WordList
        {
            get
            {
                return this.WordListField;
            }
            set
            {
                if ((object.ReferenceEquals(this.WordListField, value) != true))
                {
                    this.WordListField = value;
                    this.RaisePropertyChanged("WordList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int TotalWordsCount
        {
            get
            {
                return this.TotalWordsCountField;
            }
            set
            {
                if ((this.TotalWordsCountField.Equals(value) != true))
                {
                    this.TotalWordsCountField = value;
                    this.RaisePropertyChanged("TotalWordsCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public bool IsReady
        {
            get
            {
                return this.IsReadyField;
            }
            set
            {
                if ((this.IsReadyField.Equals(value) != true))
                {
                    this.IsReadyField = value;
                    this.RaisePropertyChanged("IsReady");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameInfo", Namespace="http://tempuri.org/")]
    public partial class GameInfo : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string ServerTimeUTCField;
        
        private int RoundElapsedTimeMSField;
        
        private int RoundDurationMSField;
        
        private int DeadTimeAmountMSField;
        
        private string RoomStateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ServerTimeUTC
        {
            get
            {
                return this.ServerTimeUTCField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ServerTimeUTCField, value) != true))
                {
                    this.ServerTimeUTCField = value;
                    this.RaisePropertyChanged("ServerTimeUTC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int RoundElapsedTimeMS
        {
            get
            {
                return this.RoundElapsedTimeMSField;
            }
            set
            {
                if ((this.RoundElapsedTimeMSField.Equals(value) != true))
                {
                    this.RoundElapsedTimeMSField = value;
                    this.RaisePropertyChanged("RoundElapsedTimeMS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int RoundDurationMS
        {
            get
            {
                return this.RoundDurationMSField;
            }
            set
            {
                if ((this.RoundDurationMSField.Equals(value) != true))
                {
                    this.RoundDurationMSField = value;
                    this.RaisePropertyChanged("RoundDurationMS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int DeadTimeAmountMS
        {
            get
            {
                return this.DeadTimeAmountMSField;
            }
            set
            {
                if ((this.DeadTimeAmountMSField.Equals(value) != true))
                {
                    this.DeadTimeAmountMSField = value;
                    this.RaisePropertyChanged("DeadTimeAmountMS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string RoomState
        {
            get
            {
                return this.RoomStateField;
            }
            set
            {
                if ((object.ReferenceEquals(this.RoomStateField, value) != true))
                {
                    this.RoomStateField = value;
                    this.RaisePropertyChanged("RoomState");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebBogglerServer.IServiceWebBoggler")]
    public interface IServiceWebBoggler
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWebBoggler/GetBoard", ReplyAction="http://tempuri.org/IServiceWebBoggler/GetBoardResponse")]
        System.Threading.Tasks.Task<WebBogglerServer.GetBoardResponse> GetBoardAsync(WebBogglerServer.GetBoardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWebBoggler/CheckWord", ReplyAction="http://tempuri.org/IServiceWebBoggler/CheckWordResponse")]
        System.Threading.Tasks.Task<WebBogglerServer.CheckWordResponse> CheckWordAsync(WebBogglerServer.CheckWordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWebBoggler/SendWordList", ReplyAction="http://tempuri.org/IServiceWebBoggler/SendWordListResponse")]
        System.Threading.Tasks.Task<WebBogglerServer.SendWordListResponse> SendWordListAsync(WebBogglerServer.SendWordListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWebBoggler/Join", ReplyAction="http://tempuri.org/IServiceWebBoggler/JoinResponse")]
        System.Threading.Tasks.Task<WebBogglerServer.JoinResponse> JoinAsync(WebBogglerServer.JoinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWebBoggler/Leave", ReplyAction="http://tempuri.org/IServiceWebBoggler/LeaveResponse")]
        System.Threading.Tasks.Task<WebBogglerServer.LeaveResponse> LeaveAsync(WebBogglerServer.LeaveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWebBoggler/GetPlayers", ReplyAction="http://tempuri.org/IServiceWebBoggler/GetPlayersResponse")]
        System.Threading.Tasks.Task<WebBogglerServer.GetPlayersResponse> GetPlayersAsync(WebBogglerServer.GetPlayersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWebBoggler/GetSolution", ReplyAction="http://tempuri.org/IServiceWebBoggler/GetSolutionResponse")]
        System.Threading.Tasks.Task<WebBogglerServer.GetSolutionResponse> GetSolutionAsync(WebBogglerServer.GetSolutionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWebBoggler/Observe", ReplyAction="http://tempuri.org/IServiceWebBoggler/ObserveResponse")]
        System.Threading.Tasks.Task<WebBogglerServer.ObserveResponse> ObserveAsync(WebBogglerServer.ObserveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWebBoggler/IsServerAlive", ReplyAction="http://tempuri.org/IServiceWebBoggler/IsServerAliveResponse")]
        System.Threading.Tasks.Task<bool> IsServerAliveAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBoardRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBoard", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.GetBoardRequestBody Body;
        
        public GetBoardRequest()
        {
        }
        
        public GetBoardRequest(WebBogglerServer.GetBoardRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBoardRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string localeID;
        
        public GetBoardRequestBody()
        {
        }
        
        public GetBoardRequestBody(string localeID)
        {
            this.localeID = localeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBoardResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBoardResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.GetBoardResponseBody Body;
        
        public GetBoardResponse()
        {
        }
        
        public GetBoardResponse(WebBogglerServer.GetBoardResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBoardResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebBogglerServer.Board GetBoardResult;
        
        public GetBoardResponseBody()
        {
        }
        
        public GetBoardResponseBody(WebBogglerServer.Board GetBoardResult)
        {
            this.GetBoardResult = GetBoardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckWordRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckWord", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.CheckWordRequestBody Body;
        
        public CheckWordRequest()
        {
        }
        
        public CheckWordRequest(WebBogglerServer.CheckWordRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckWordRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string word;
        
        public CheckWordRequestBody()
        {
        }
        
        public CheckWordRequestBody(string word)
        {
            this.word = word;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckWordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckWordResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.CheckWordResponseBody Body;
        
        public CheckWordResponse()
        {
        }
        
        public CheckWordResponse(WebBogglerServer.CheckWordResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckWordResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckWordResult;
        
        public CheckWordResponseBody()
        {
        }
        
        public CheckWordResponseBody(bool CheckWordResult)
        {
            this.CheckWordResult = CheckWordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWordListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWordList", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.SendWordListRequestBody Body;
        
        public SendWordListRequest()
        {
        }
        
        public SendWordListRequest(WebBogglerServer.SendWordListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendWordListRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebBogglerServer.WordList wordList;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ClientID;
        
        public SendWordListRequestBody()
        {
        }
        
        public SendWordListRequestBody(WebBogglerServer.WordList wordList, string ClientID)
        {
            this.wordList = wordList;
            this.ClientID = ClientID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWordListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWordListResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.SendWordListResponseBody Body;
        
        public SendWordListResponse()
        {
        }
        
        public SendWordListResponse(WebBogglerServer.SendWordListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendWordListResponseBody
    {
        
        public SendWordListResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JoinRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Join", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.JoinRequestBody Body;
        
        public JoinRequest()
        {
        }
        
        public JoinRequest(WebBogglerServer.JoinRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JoinRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        public JoinRequestBody()
        {
        }
        
        public JoinRequestBody(string clientID, string name)
        {
            this.clientID = clientID;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JoinResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JoinResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.JoinResponseBody Body;
        
        public JoinResponse()
        {
        }
        
        public JoinResponse(WebBogglerServer.JoinResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JoinResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool JoinResult;
        
        public JoinResponseBody()
        {
        }
        
        public JoinResponseBody(bool JoinResult)
        {
            this.JoinResult = JoinResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LeaveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Leave", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.LeaveRequestBody Body;
        
        public LeaveRequest()
        {
        }
        
        public LeaveRequest(WebBogglerServer.LeaveRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LeaveRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientID;
        
        public LeaveRequestBody()
        {
        }
        
        public LeaveRequestBody(string clientID)
        {
            this.clientID = clientID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LeaveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LeaveResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.LeaveResponseBody Body;
        
        public LeaveResponse()
        {
        }
        
        public LeaveResponse(WebBogglerServer.LeaveResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LeaveResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LeaveResult;
        
        public LeaveResponseBody()
        {
        }
        
        public LeaveResponseBody(bool LeaveResult)
        {
            this.LeaveResult = LeaveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPlayersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPlayers", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.GetPlayersRequestBody Body;
        
        public GetPlayersRequest()
        {
        }
        
        public GetPlayersRequest(WebBogglerServer.GetPlayersRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPlayersRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientID;
        
        public GetPlayersRequestBody()
        {
        }
        
        public GetPlayersRequestBody(string clientID)
        {
            this.clientID = clientID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPlayersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPlayersResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.GetPlayersResponseBody Body;
        
        public GetPlayersResponse()
        {
        }
        
        public GetPlayersResponse(WebBogglerServer.GetPlayersResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPlayersResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebBogglerServer.Players GetPlayersResult;
        
        public GetPlayersResponseBody()
        {
        }
        
        public GetPlayersResponseBody(WebBogglerServer.Players GetPlayersResult)
        {
            this.GetPlayersResult = GetPlayersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSolutionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSolution", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.GetSolutionRequestBody Body;
        
        public GetSolutionRequest()
        {
        }
        
        public GetSolutionRequest(WebBogglerServer.GetSolutionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSolutionRequestBody
    {
        
        public GetSolutionRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSolutionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSolutionResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.GetSolutionResponseBody Body;
        
        public GetSolutionResponse()
        {
        }
        
        public GetSolutionResponse(WebBogglerServer.GetSolutionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSolutionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebBogglerServer.WordList GetSolutionResult;
        
        public GetSolutionResponseBody()
        {
        }
        
        public GetSolutionResponseBody(WebBogglerServer.WordList GetSolutionResult)
        {
            this.GetSolutionResult = GetSolutionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObserveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Observe", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.ObserveRequestBody Body;
        
        public ObserveRequest()
        {
        }
        
        public ObserveRequest(WebBogglerServer.ObserveRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObserveRequestBody
    {
        
        public ObserveRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObserveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObserveResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBogglerServer.ObserveResponseBody Body;
        
        public ObserveResponse()
        {
        }
        
        public ObserveResponse(WebBogglerServer.ObserveResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObserveResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebBogglerServer.GameInfo ObserveResult;
        
        public ObserveResponseBody()
        {
        }
        
        public ObserveResponseBody(WebBogglerServer.GameInfo ObserveResult)
        {
            this.ObserveResult = ObserveResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IServiceWebBogglerChannel : WebBogglerServer.IServiceWebBoggler, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ServiceWebBogglerClient : System.ServiceModel.ClientBase<WebBogglerServer.IServiceWebBoggler>, WebBogglerServer.IServiceWebBoggler
    {
        
        /// <summary>
        /// Implementare questo metodo parziale per configurare l'endpoint servizio.
        /// </summary>
        /// <param name="serviceEndpoint">Endpoint da configurare</param>
        /// <param name="clientCredentials">Credenziali del client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceWebBogglerClient() : 
                base(ServiceWebBogglerClient.GetDefaultBinding(), ServiceWebBogglerClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceWebBoggler.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceWebBogglerClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceWebBogglerClient.GetBindingForEndpoint(endpointConfiguration), ServiceWebBogglerClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceWebBogglerClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceWebBogglerClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceWebBogglerClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceWebBogglerClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceWebBogglerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebBogglerServer.GetBoardResponse> WebBogglerServer.IServiceWebBoggler.GetBoardAsync(WebBogglerServer.GetBoardRequest request)
        {
            return base.Channel.GetBoardAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebBogglerServer.GetBoardResponse> GetBoardAsync(string localeID)
        {
            WebBogglerServer.GetBoardRequest inValue = new WebBogglerServer.GetBoardRequest();
            inValue.Body = new WebBogglerServer.GetBoardRequestBody();
            inValue.Body.localeID = localeID;
            return ((WebBogglerServer.IServiceWebBoggler)(this)).GetBoardAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebBogglerServer.CheckWordResponse> WebBogglerServer.IServiceWebBoggler.CheckWordAsync(WebBogglerServer.CheckWordRequest request)
        {
            return base.Channel.CheckWordAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebBogglerServer.CheckWordResponse> CheckWordAsync(string word)
        {
            WebBogglerServer.CheckWordRequest inValue = new WebBogglerServer.CheckWordRequest();
            inValue.Body = new WebBogglerServer.CheckWordRequestBody();
            inValue.Body.word = word;
            return ((WebBogglerServer.IServiceWebBoggler)(this)).CheckWordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebBogglerServer.SendWordListResponse> WebBogglerServer.IServiceWebBoggler.SendWordListAsync(WebBogglerServer.SendWordListRequest request)
        {
            return base.Channel.SendWordListAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebBogglerServer.SendWordListResponse> SendWordListAsync(WebBogglerServer.WordList wordList, string ClientID)
        {
            WebBogglerServer.SendWordListRequest inValue = new WebBogglerServer.SendWordListRequest();
            inValue.Body = new WebBogglerServer.SendWordListRequestBody();
            inValue.Body.wordList = wordList;
            inValue.Body.ClientID = ClientID;
            return ((WebBogglerServer.IServiceWebBoggler)(this)).SendWordListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebBogglerServer.JoinResponse> WebBogglerServer.IServiceWebBoggler.JoinAsync(WebBogglerServer.JoinRequest request)
        {
            return base.Channel.JoinAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebBogglerServer.JoinResponse> JoinAsync(string clientID, string name)
        {
            WebBogglerServer.JoinRequest inValue = new WebBogglerServer.JoinRequest();
            inValue.Body = new WebBogglerServer.JoinRequestBody();
            inValue.Body.clientID = clientID;
            inValue.Body.name = name;
            return ((WebBogglerServer.IServiceWebBoggler)(this)).JoinAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebBogglerServer.LeaveResponse> WebBogglerServer.IServiceWebBoggler.LeaveAsync(WebBogglerServer.LeaveRequest request)
        {
            return base.Channel.LeaveAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebBogglerServer.LeaveResponse> LeaveAsync(string clientID)
        {
            WebBogglerServer.LeaveRequest inValue = new WebBogglerServer.LeaveRequest();
            inValue.Body = new WebBogglerServer.LeaveRequestBody();
            inValue.Body.clientID = clientID;
            return ((WebBogglerServer.IServiceWebBoggler)(this)).LeaveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebBogglerServer.GetPlayersResponse> WebBogglerServer.IServiceWebBoggler.GetPlayersAsync(WebBogglerServer.GetPlayersRequest request)
        {
            return base.Channel.GetPlayersAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebBogglerServer.GetPlayersResponse> GetPlayersAsync(string clientID)
        {
            WebBogglerServer.GetPlayersRequest inValue = new WebBogglerServer.GetPlayersRequest();
            inValue.Body = new WebBogglerServer.GetPlayersRequestBody();
            inValue.Body.clientID = clientID;
            return ((WebBogglerServer.IServiceWebBoggler)(this)).GetPlayersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebBogglerServer.GetSolutionResponse> WebBogglerServer.IServiceWebBoggler.GetSolutionAsync(WebBogglerServer.GetSolutionRequest request)
        {
            return base.Channel.GetSolutionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebBogglerServer.GetSolutionResponse> GetSolutionAsync()
        {
            WebBogglerServer.GetSolutionRequest inValue = new WebBogglerServer.GetSolutionRequest();
            inValue.Body = new WebBogglerServer.GetSolutionRequestBody();
            return ((WebBogglerServer.IServiceWebBoggler)(this)).GetSolutionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebBogglerServer.ObserveResponse> WebBogglerServer.IServiceWebBoggler.ObserveAsync(WebBogglerServer.ObserveRequest request)
        {
            return base.Channel.ObserveAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebBogglerServer.ObserveResponse> ObserveAsync()
        {
            WebBogglerServer.ObserveRequest inValue = new WebBogglerServer.ObserveRequest();
            inValue.Body = new WebBogglerServer.ObserveRequestBody();
            return ((WebBogglerServer.IServiceWebBoggler)(this)).ObserveAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<bool> IsServerAliveAsync()
        {
            return base.Channel.IsServerAliveAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceWebBoggler))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("L\'endpoint denominato \'{0}\' non è stato trovato.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceWebBoggler))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:5733/ServiceWebBoggler.svc");
            }
            throw new System.InvalidOperationException(string.Format("L\'endpoint denominato \'{0}\' non è stato trovato.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceWebBogglerClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceWebBoggler);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceWebBogglerClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceWebBoggler);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceWebBoggler,
        }
    }
}
